#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) notify-send -w "Top CPU Processes:
$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac

long=$(sensors | awk '/^Package/ {print $4}' | tr -d "+")
# Output: 51.0°C

# Prints only first 2 characters of string
short="${long:0:2}"

echo "${short}°C"
