#!/usr/bin/env bash

case $BLOCK_BUTTON in
	1) notify-send -w "Public IP
ipv4  $(curl -4 ident.me)
ipv6  $(curl -6 icanhazip.com)" ;;
esac

ADDR=$(ip route get 1.1.1.1 | cut -d " " -f7)
IFACE=$(ip route get 1.1.1.1 | awk '{print $5}')

echo "$IFACE: $ADDR"
