#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) notify-send -w "acpi -b
$(acpi -b)" ;;
esac

BAT=$(acpi -b | grep -E -o '[0-9][0-9]*%')

echo $BAT

# Set urgent flag below 5% or use orange below 20%
if [ "$BAT_VALUE" -le 5 ]; then
    exit 33
elif [ "$BAT_VALUE" -le 20 ]; then
    echo "#FF8000"
fi

exit 0

