#!/usr/bin/env sh

case $BLOCK_BUTTON in
        1) notify-send -w "Top RAM Processes:
$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
esac

USED=$(free -m | awk '/^Mem:/ {print $3}')
TOTL=$(free -m | awk '/^Mem:/ {print $2}')

PERC=$(echo "scale=2 ; $USED / $TOTL" | bc | tr -d ".")

echo "$PERC%"
